### ISSUE TITLE
np.int is deprecated in numpy since NumPy 1.20

### ISSUE THREAD

**Issue by Arturossi** [allydunham/sequence_unet#2]
When installing sequence_unet it requires the newest numpy version. And the np.int has been deprecated since version 1.20. When running it prompts the following error message when using numpy version 1.24.2.

```python
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

It is possible to fix this just by changing from np.int one of the following int, np.int32 or np.int64 in the file 'sequence_unet/sequence_unet/predict.py' on line 47

**Comment by allydunham** [comment]
Thanks, I thought I had tested on the most up to date numpy versions but obviously not. I'll go through and update all the deprecated references (looks like np.float etc. have changed too) and should get a fix out later this week.

I'd hoped to leave the package requirements fairly broad but I may end up having to pin them at some point, particularly if any major tensorflow changes come through.

**Comment by allydunham** [comment]
I have now updated all of these. I can't test fully since the latest version of numpy conflicts with the tensorflow-macos package I have to use, but this should be solve the problem.
