### ISSUE TITLE
Error occurs in the function "freqs_to_pssm" 

### ISSUE THREAD

**Issue by zchwang** [allydunham/sequence_unet#5]
Hi，

"There seems to be an error on line 96 of the "predict.py" script. Should "AA_FREQS[:,None]" be changed to "AA_FREQS[None, :]"?

Best regards!
Zechen

**Comment by allydunham** [comment]
Thanks Zechen, good catch. I missed that when the model output dimension order changed between the development model and the final package. Should be fixed now I think.
